### ISSUE TITLE
使用WidgetsFlutterBinding.ensureInitialized()会报错

### ISSUE THREAD

**Issue by git-maven** [qcks/flutter_screen_ratio_adapter#1]
由于项目中需要在启动app使用WidgetsFlutterBinding.ensureInitialized()
用flutter_screen_ratio_adapter会出现这种报错,如图
![1C37D6FA-680A-46A7-8C78-25A2B2D27401](https://user-images.githubusercontent.com/45022397/80551991-dadc0080-89f7-11ea-9083-d55be8fbfd0f.png)

**Comment by qcks** [comment]
已经解决
