### ISSUE TITLE
已经存在的项目上集成Flutter . 使用此库报错。

### ISSUE THREAD

**Issue by ymex** [qcks/flutter_screen_ratio_adapter#10]
Another exception was thrown: BoxConstraints has a NaN value in minHeight.
Another exception was thrown: 'package:flutter/src/rendering/view.dart': Failed assertion: line 164 pos 12: '_size.isFinite': is not true.
直接启动 flutter 项目不会出错。

**Comment by qcks** [comment]
这么少？起码flutter doctor一下吧，🤫明天有新版本哦
