### ISSUE TITLE
使用flutter_driver的时候报错

### ISSUE THREAD

**Issue by Dhuliang** [qcks/flutter_screen_ratio_adapter#11]
为了集成e2e测试 , 发现以下

type '_DriverBinding' is not a subtype of type 'WidgetsFlutterBinding'

**Comment by qcks** [comment]
> 为了集成e2e测试，发现以下
> 
> '_DriverBinding'类型不是'WidgetsFlutterBinding'类型的子类型

1.这个问题很简单
`void main() {
  // This line enables the extension.
  enableFlutterDriverExtension();

  // Call the `main()` function of the app, or call `runApp` with
  // any widget you are interested in testing.
  app.main();
}`
enableFlutterDriverExtension出来的应该是_DriverBinding,而WidgetsFlutterBinding是Flutter SDK中的Binding
_DriverBinding  as WidgetsFlutterBinding?false
2.怎么解决我不管。
你可以自己Fork项目集成flutter_driver，然后改一个Binding.就这样。
