### ISSUE TITLE
build web后在iphone12中右侧空白一块

### ISSUE THREAD

**Issue by yanzhandong** [qcks/flutter_screen_ratio_adapter#13]
![image](https://user-images.githubusercontent.com/7776110/120172874-10c06980-c236-11eb-95e0-e3c22e928ab2.png)
所有页面都是这样

去掉flutter_screen_ratio_adapter后恢复正常，可以排除我代码的问题

**Comment by qcks** [comment]
看看你在runApp之前有没有调用
  WidgetsFlutterBinding.ensureInitialized();？
如果有：置换到 onEnsureInitialized 函数下；
如果没有：上代码
