### ISSUE TITLE
适配方案应该是最优的方式，但是实际应用过程中有遇到一条线的问题

### ISSUE THREAD

**Issue by LiLinXiang** [qcks/flutter_screen_ratio_adapter#14]
![image](https://user-images.githubusercontent.com/19835545/123981099-a6494780-d9f4-11eb-836c-34e1f87cd451.png)

![image](https://user-images.githubusercontent.com/19835545/123981430-e1e41180-d9f4-11eb-82ec-61f139c6f765.png)

AppBar， elevation设置为0 后，AppBar和内容之间会有一条缝隙。目前通过此方法处理，但是在不同设备上还是会出现，应该是尺寸转化的问题

`
appBar: AppBar(
        title: Text('首页'),
        centerTitle: true,
        elevation: 0,
        // 解决一条线问题
        bottom: PreferredSize(
          preferredSize: Size.fromHeight(0.2),
          child: SizedBox(),
        ),
      ),
`

**Comment by qcks** [comment]
@@@未能复现。请贴出可复现的最小代码。@LiLinXiang
<img width="783" alt="截屏2021-07-02 上午9 47 02" src="https://user-images.githubusercontent.com/21257035/124208615-7d22d700-db1a-11eb-8485-312c58203e8d.png">

**Comment by LiLinXiang** [comment]
@@@标题栏和底部主体部件同色，背景色调整为白色方便观察。会出现一条间隙
![image](https://user-images.githubusercontent.com/19835545/124236196-bffba380-db48-11eb-8dfb-fdd67b0c66a9.png)
![image](https://user-images.githubusercontent.com/19835545/124236271-d3a70a00-db48-11eb-9272-bee8f5419cca.png)

`import 'package:flutter/material.dart';

class RepetitionLine extends StatelessWidget {
  RepetitionLine({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        primaryColor: Color(0xFF007D5F),
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('复现线条间隙问题'),
          elevation: 0,
          // 通过以下代码，控制好阈值能消除间隙
          /*bottom: PreferredSize(
            preferredSize: Size.fromHeight(0.1),
            child: SizedBox(),
          ),*/
        ),
        backgroundColor: Colors.white,
        body: Container(
          width: double.infinity,
          height: 200,
          color: Color(0xFF007D5F),
        ),
      ),
    );
  }
}`

**Comment by qcks** [comment]
```
                  Container(color: Colors.red, height: : 50.6),
                  Container(color: Colors.red, height: : 50.6),
              Row(
                children: [
                  Container(color: Colors.red, height: 50, width: 50.6),
                  Container(color: Colors.red, height: 50, width: 50.6),
                  Container(color: Colors.red, height: 50, width: 50.6),
                ],
```
这是最小代码。
问题原因可能是精度丢失。
此问题必现于：相同色块Widget相邻时。设置同色背景解决。
使用appbar时建议嵌套Scaffold
```
Scaffold(
      body: Column(
        children: [
          SizedBox(
            height: 300,
            child: Scaffold(
              appBar: AppBar(
                  title: Text('复现线条间隙问题'),
                  elevation: 0,
                  backgroundColor: Color(0xFF007D5F)),
              backgroundColor: Color(0xFF007D5F),
              body: Container(color: Color(0xFF007D5F), height: 200),
            ),
          ),
        ],
      ),
    )
```

**Comment by LiLinXiang** [comment]
可能是Flutter本身问题，这个issues有反馈，：https://github.com/flutter/flutter/issues/14288

**Comment by qcks** [comment]
> 可能是 Flutter 手工问题，这个问题有反馈，：[flutter/flutter#14288](https://github.com/flutter/flutter/issues/14288)

嗯 确实是谷歌的锅，但是你白嫖不点赞也被我抓住了🤔

**Comment by LiLinXiang** [comment]
哈哈哈~~，已关注点赞。在转化为物理尺寸时，四舍五入取整呢，是否可以解决
