### ISSUE TITLE
FxTransitionBuilder 无法使用全局隐藏键盘

### ISSUE THREAD

**Issue by stylehuan** [qcks/flutter_screen_ratio_adapter#16]
目前全局空白区域控制键盘的方式是这样的

```
builder: (context, child) => Scaffold(
  // Global GestureDetector that will dismiss the keyboard
  body: GestureDetector(
    onTap: () {
      hideKeyboard(context);
    },
    child: child,
  ),
),
```

使用builder: FxTransitionBuilder(builder: null) 后就没全局控制

**Comment by qcks** [comment]
你倒是贴上代码(hideKeyboard)啊  @stylehuan

**Comment by stylehuan** [comment]
> 你倒是贴上代码(hideKeyboard)啊 @stylehuan
问题不是隐藏键盘，我描述不准确。是输入框获取焦点后被顶飞了。可能跟我配置的uisize有关系，看readme不太明白应该如何配置设计稿。我目前的设计稿是  375 * 812。所以，我配置的也是  BlueprintsRectangle(375, 812)。
