### ISSUE TITLE
MediaQuery.of(context).size.width

### ISSUE THREAD

**Issue by asd39715** [qcks/flutter_screen_ratio_adapter#17]
MediaQuery.of(context).size.width不兼容屏幕，自己的代码可以根据您提供的方式来适配，但很多第三方插件不兼容，请问有解决方法吗？

**Comment by qcks** [comment]
这是全局适配 @asd39715

**Comment by qcks** [comment]
不知所云

**Comment by asd39715** [comment]
@qcks 您好，MediaQuery.of(context).size.width是获取屏幕宽度，如果用了您的插件之后，这个值会改变了，如果项目上中使用了其他第三方插件，同样使用了该方法，在ipad上会导致越界，在部分手机中该值会变小导致变型，而其他第三方插件修改更新会很麻烦，请问题有何解决方法？
