### ISSUE TITLE
MediaQuery.of(context).size.width

### ISSUE THREAD

**Issue by asd39715** [qcks/flutter_screen_ratio_adapter#18]
@qcks 您好，MediaQuery.of(context).size.width是获取屏幕宽度，如果用了您的插件之后，这个值会改变了，如果项目上中使用了其他第三方插件，同样使用了该方法，在ipad上会导致越界，在部分手机中该值会变小导致变型，而其他第三方插件修改更新会很麻烦，请问题有何解决方法？

**Comment by qcks** [comment]
贴一下三方插件是怎么用MediaQuery.of(context).size的，我看看

**Comment by asd39715** [comment]
@qcks 您好，我使用了腾讯云TRTC，代码如下
Scaffold(
      key: _scaffoldKey,
      body: WillPopScope(
        onWillPop: () async {
          trtcCloud.exitRoom();
          return true;
        },
        child: Stack(
          children: <Widget>[
            ListView.builder(
                scrollDirection: Axis.horizontal,
                itemCount: screenUserList.length,
                cacheExtent: 0,
                controller: scrollControl,
                itemBuilder: (BuildContext context, index) {
                  var item = screenUserList[index];
                  return Container(
                    width: MediaQuery.of(context).size.width,
                    height: MediaQuery.of(context).size.height,
                    color: Color.fromRGBO(19, 41, 75, 1),
                    child: Wrap(
                      children: List.generate(
                        item.length,
                        (index) => LayoutBuilder(
                          key: ValueKey(item[index]['userId'] +
                              item[index]['type'] +
                              item[index]['size']['width'].toString()),
                          builder: (BuildContext context,
                              BoxConstraints constraints) {
                            Size size = MeetingTool.getViewSize(
                                MediaQuery.of(context).size,
                                userList.length,
                                index,
                                item.length);
                            double width = size.width;
                            double height = size.height;
                            //双击放大后
                            if (isDoubleTap) {
                              //其他视频渲染宽高设置为1，否则视频不推流
                              if (item[index]['size']['width'] == 0) {
                                width = 1;
                                height = 1;
                              }
                            }
                            ValueKey valueKey = ValueKey(item[index]['userId'] +
                                item[index]['type'] +
                                (isDoubleTap ? "1" : "0"));
                            if (item[index]['size']['width'] > 0) {
                              width = double.parse(
                                  item[index]['size']['width'].toString());
                              height = double.parse(
                                  item[index]['size']['height'].toString());
                            }
                            print("==valueKey=" + valueKey.toString());
                            return Container(
                              key: valueKey,
                              height: height,
                              width: width,
                              child: Stack(
                                key: valueKey,
                                children: <Widget>[
                                  renderView(item[index], valueKey),
                                  videoVoice(item[index])
                                ],
                              ),
                            );
                          },
                        ),
                      ),
                    ),
                  );
                }),
            topSetting(),
            beautySetting(),
            bottomSetting()
          ],
        ),
      ),
    )

**Comment by qcks** [comment]
更新到3.0.0。你们这是套demo式开发吗

**Comment by asd39715** [comment]
不是demo式开发，只是视频相关的功能，引用了腾讯云的trtc，使用您的插件之后，提示
[log] 【_Fx】 △L=79.5277777777777 状态栏△L=1.2500000000000036 _bodyMaxLength=715.2777777777777
[log] 【_Fx】 设计稿标准尺寸 = BlueprintsRectangle{width: 375.0, length: 667.0} h/w tgθ= 1.7786666666666666
[log] 【_Fx】 设备的屏幕尺寸 =Size(1080.0, 2150.0)  h/w tgθ=1.9907407407407405
[log] 【_Fx】 尺码过小 △L=79.5277777777777 设置需要留白的区域
[log] 【_Fx】 原本屏幕尺寸比率=3.0
[log] 【_Fx】 转换后的屏幕尺寸比率=2.88

**Comment by qcks** [comment]
> @qcks 您好，MediaQuery.of(context).size.width是获取屏幕宽度，如果用了您的插件之后，这个值会改变了，如果项目上中使用了其他第三方插件，同样使用了该方法，在ipad上会导致越界，在部分手机中该值会变小导致变型，而其他第三方插件修改更新会很麻烦，请问题有何解决方法？

不要开重复issue！
