### ISSUE TITLE
底部TextField弹起键盘，TextField被键盘遮挡

### ISSUE THREAD

**Issue by binjiayou66** [qcks/flutter_screen_ratio_adapter#4]
集成该屏幕适配插件后，写一个页面，结构大概如下：
Column(
  Flexible( Container() ),
  TextField(),
  SafeArea(),
)
当点击TextField键盘弹起时，在较多安卓手机中TextField会被部分遮挡（如华为Meta 30），在iOS较老机型中会被完全遮挡（如iPhone 5/5s/5C）。

不知道可有解决方案？

**Comment by binjiayou66** [comment]
测试了一下，系统键盘弹起，页面被顶起高度不正确，所有滚动视图的滚动范围都会受影响，这是一个大问题

**Comment by binjiayou66** [comment]
应该这么描述：该库解决的只是UI渲染适配，在运行期间，凡是系统引发的UI改变（如常用的MediaQuery.of(context).viewInsets、MediaQuery.of(context).padding等），都会发生偏差。

最常见的就是键盘问题，目前的做法比较麻烦：
1.设置Scaffold节点的resizeToAvoidBottomInset属性为false，使当前页面不会根据BottomInset发生改变而自动resize
2.在build方法中手动获取MediaQuery.of(context).viewInsets.bottom，通过计算得出正确的底部padding值，在布局中手动增加Padding来进行垫高

**Comment by qcks** [comment]
因为你的设计稿是按照某个ios标准机型设计的，而老ios机型与其他android机型屏幕长宽比率与其不同。本方案宽度适配，原理也很简单；总之设备已经知道了身着的设计稿是否合身；后续会考虑计算出高度差值，这个值是固定的。

**Comment by qcks** [comment]
> 应该这么描述：该库解决的只是UI渲染适应，在运行期间，凡是系统引发的UI改变（如常用的MediaQuery.of（上下文）.viewInsets，MediaQuery.of（上下文）.padding等），都会发生偏差。
> 
> 最常见的就是键盘问题，目前的做法比较麻烦：
> 1.设置Scaffold例程的resizeToAvoidBottomInset属性为false，使当前页面不会根据BottomInset发生更改而自动调整大小
> 2.在构建方法中手动获取MediaQuery.of（上下文） .viewInsets.bottom，通过计算得出正确的底部padding值，在布局中手动增加Padding来进行垫高

update即可
