### ISSUE TITLE
最新版报错Error:'FxTransitionBuilder' is not configured

### ISSUE THREAD

**Issue by trustyboy** [qcks/flutter_screen_ratio_adapter#8]
最新版以下这种方式：
```
  @override
  Widget build(BuildContext context) {
    return ScopedModel<AppModel>(
        model: AppModel(),
        child: MaterialApp(
            title: Config.APP_NAME,
            theme: ThemeData.dark(),
            home: LoginPage(),
            builder: FxTransitionBuilder(
              builder: null,
            )));
  }

```
报错，如果不包ScopedModel倒是正常，可是需要用ScopedModel换主题，是否有其他写法？

Error:'FxTransitionBuilder' is not configured
MaterialApp(
  ......
  builder: FxTransitionBuilder(builder: null),
  ......
);
'package:screen_ratio_adapter/src/screen_adapter_binding.dart':
Failed assertion: line 196 pos 9: '_checkApp(super.child, context)'

**Comment by qcks** [comment]
dependencies:
  xxxxxx:
    git:
      url: git://github.com/flutter/xxxx.git
用github链接库

**Comment by qcks** [comment]
后续一般不发布到pub仓库

**Comment by wonderful89** [comment]
example 里面 `builder: FxTransitionBuilder(builder: null),//勿忘` 这一句应该打开注释吧? @qcks
