### ISSUE TITLE
runFxApp会检测传入的widget必须为MaterialApp，是否可以改进

### ISSUE THREAD

**Issue by roger66** [qcks/flutter_screen_ratio_adapter#9]
我在项目中使用provider时需要在MaterialApp外套一层provider，由于runFxApp检测了传入的widget就用不了这个适配方案了

**Comment by qcks** [comment]
引用GitHub库，或者pub更新到1.0.1

**Comment by roger66** [comment]
有新的问题，不用provider正常

**Comment by roger66** [comment]
出现了新的问题，不用provider正常
![1609126963(1)](https://user-images.githubusercontent.com/16676365/103188140-46b59680-4902-11eb-8936-a197ef797433.png)
下面是使用的代码
![1609127241(1)](https://user-images.githubusercontent.com/16676365/103188233-95633080-4902-11eb-9e27-197855306e5a.jpg)
![1609127241](https://user-images.githubusercontent.com/16676365/103188234-95fbc700-4902-11eb-9479-601608e92986.jpg)

**Comment by qcks** [comment]
> 出现了新的问题，不用provider正常
> ![1609126963(1)](https://user-images.githubusercontent.com/16676365/103188140-46b59680-4902-11eb-8936-a197ef797433.png)
> 下面是使用的代码
> ![1609127241(1)](https://user-images.githubusercontent.com/16676365/103188233-95633080-4902-11eb-9e27-197855306e5a.jpg)
> ![1609127241](https://user-images.githubusercontent.com/16676365/103188234-95fbc700-4902-11eb-9479-601608e92986.jpg)

写了一个bug，引用最新GitHub库，或者pub更新到1.0.2；

**Comment by qcks** [comment]
> > 出现了新的问题，不用provider正常
> > ![1609126963(1)](https://user-images.githubusercontent.com/16676365/103188140-46b59680-4902-11eb-8936-a197ef797433.png)
> > 下面是使用的代码
> > ![1609127241(1)](https://user-images.githubusercontent.com/16676365/103188233-95633080-4902-11eb-9e27-197855306e5a.jpg)
> > ![1609127241](https://user-images.githubusercontent.com/16676365/103188234-95fbc700-4902-11eb-9479-601608e92986.jpg)
> 
>  @roger66 写了一个bug，引用最新GitHub库，或者pub更新到1.0.2；

**Comment by qcks** [comment]
更新到1.0.2;代码自检测不再依赖CupertinoApp或MaterialApp

**Comment by roger66** [comment]
> 更新到1.0.2;代码自检测不再依赖CupertinoApp或MaterialApp

可以，很优秀
